variables:
  UV_VERSION: 0.5
  PYTHON_VERSION: 3.13
  BASE_LAYER: bookworm-slim
  UV_CACHE_DIR: .uv-cache
  UV_SYSTEM_PYTHON: 1

stages:
  - test

pytest:
  stage: test
  image: ghcr.io/astral-sh/uv:$UV_VERSION-python$PYTHON_VERSION-$BASE_LAYER
  cache:
    - key:
        files:
          - uv.lock
      paths:
        - $UV_CACHE_DIR
  script:
    - uv sync --all-extras
    - uv run pytest
  coverage: /TOTAL.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/
  artifacts:
    reports:
      junit: reports/tests/report.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage/coverage.xml
